openapi: 3.1.0
info:
  title: Sealed Secret Microservice
  description: a
  version: 1.0.0
tags:
  - name: secret
    description: Everything about your secrets
paths:
  /secrets/seal:
    post:
      tags:
        - secret
      summary: Seal a secret.
      description: Seal a secret.
      operationId: sealSecret
      requestBody:
        $ref: "#/components/requestBodies/Secret"
      responses:
        "200":
          $ref: "#/components/responses/SealedSecret"
        "400":
          description: Invalid Input
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/Error"
                  - properties:
                      code:
                        enum:
                          - 400
        "422":
          description: Validation exception
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/Error"
                  - properties:
                      code:
                        enum:
                          - 422
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Secret:
      required:
        - name
        - namespace
        - certificate
        - data
      type: object
      properties:
        name:
          type: string
        namespace:
          type: string
        certificate:
          type: string
        data:
          type: object
          minItems: 1
          patternProperties:
            "^[a-zA-Z0-9._-]+$":
              type: string
          properties: {}
    Error:
      type: object
      properties:
        code:
          type: integer
          minimum: 400
          maximum: 600
          exclusiveMaximum: true
        message:
          type: string
      required:
        - code
        - message
  requestBodies:
    Secret:
      required: true
      description: Secret object that needs to be sealed
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Secret"
  responses:
    SealedSecret:
      description: Successful operation
      content:
        application/json:
          schema:
            type: object
            properties:
              apiVersion:
                type: string
              kind:
                type: string
              metadata:
                type: object
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
              spec:
                description: SealedSecretSpec is the specification of a SealedSecret.
                properties:
                  encryptedData:
                    additionalProperties:
                      type: string
                    type: object
                  template:
                    properties:
                      metadata:
                        properties:
                          name:
                            type: string
                          namespace:
                            type: string
                        type: object
                      type:
                        description: Used to facilitate programmatic handling of secret data.
                        type: string
                    type: object
                required:
                  - encryptedData
                type: object
            required:
              - spec
